In [139]:
import xarray as xr
import numpy as np

In [140]:
a = xr.DataArray(np.random.randint(1, 10, size=3), dims=['x'], coords=[np.arange(3)])
b = xr.DataArray(np.random.randint(1, 10, size=2), dims=['y'], coords=[np.arange(2)])
c = xr.DataArray(np.random.randint(1, 10, size=2), dims=['z'], coords=[np.arange(2)])
i = xr.DataArray(np.random.randint(1, 3, 10), dims=['i'], coords=[np.arange(10)])

In [141]:
d = a * b * i * c

In [142]:
e = xr.DataArray(np.random.randint(1, 10, size=3), dims=['x'], coords=[np.arange(3)])
f = xr.DataArray(np.random.randint(1, 10, size=2), dims=['y'], coords=[np.arange(2)])
g = xr.DataArray(np.random.randint(1, 10, size=2), dims=['z'], coords=[np.arange(2)])

In [143]:
h = e * g * f

In [144]:
h

<xarray.DataArray (x: 3, z: 2, y: 2)>
array([[[160, 160],
        [ 20,  20]],

       [[320, 320],
        [ 40,  40]],

       [[ 40,  40],
        [  5,   5]]])
Coordinates:
  * x        (x) int64 0 1 2
  * z        (z) int64 0 1
  * y        (y) int64 0 1

In [145]:
test = (d).mean('i') * h
print test

<xarray.DataArray (x: 3, y: 2, z: 2)>
array([[[  2.41920000e+04,   1.34400000e+03],
        [  9.67680000e+04,   5.37600000e+03]],

       [[  4.83840000e+04,   2.68800000e+03],
        [  1.93536000e+05,   1.07520000e+04]],

       [[  1.00800000e+03,   5.60000000e+01],
        [  4.03200000e+03,   2.24000000e+02]]])
Coordinates:
  * x        (x) int64 0 1 2
  * y        (y) int64 0 1
  * z        (z) int64 0 1


In [148]:
np.cumsum(test, axis=test.get_axis_num('y'))

<xarray.DataArray (x: 3, y: 2, z: 2)>
array([[[  2.41920000e+04,   1.34400000e+03],
        [  1.20960000e+05,   6.72000000e+03]],

       [[  4.83840000e+04,   2.68800000e+03],
        [  2.41920000e+05,   1.34400000e+04]],

       [[  1.00800000e+03,   5.60000000e+01],
        [  5.04000000e+03,   2.80000000e+02]]])
Coordinates:
  * x        (x) int64 0 1 2
  * y        (y) int64 0 1
  * z        (z) int64 0 1

In [149]:
np.cumsum(test.values, axis=test.get_axis_num('y'))

array([[[  2.41920000e+04,   1.34400000e+03],
        [  1.20960000e+05,   6.72000000e+03]],

       [[  4.83840000e+04,   2.68800000e+03],
        [  2.41920000e+05,   1.34400000e+04]],

       [[  1.00800000e+03,   5.60000000e+01],
        [  5.04000000e+03,   2.80000000e+02]]])

In [150]:
test_ = test.copy(deep=True)
for k in range(2):
    test_[{'y': k}] = test.isel(y=slice(None, k + 1)).sum('y')
print test_

In [154]:
test_ = test.copy(deep=True)
test_ = test_.transpose('y', 'x', 'z')
for k in range(2):
    test_[{'y': k}] = test.isel(y=slice(None, k + 1)).sum('y')
print test_.transpose('x', 'y', 'z')

<xarray.DataArray (x: 3, y: 2, z: 2)>
array([[[  2.41920000e+04,   1.34400000e+03],
        [  1.20960000e+05,   6.72000000e+03]],

       [[  4.83840000e+04,   2.68800000e+03],
        [  2.41920000e+05,   1.34400000e+04]],

       [[  1.00800000e+03,   5.60000000e+01],
        [  5.04000000e+03,   2.80000000e+02]]])
Coordinates:
  * x        (x) int64 0 1 2
  * y        (y) int64 0 1
  * z        (z) int64 0 1


In [156]:
test_ = test.copy(deep=True)
test_ = test_.transpose('x', 'z', 'y')
for k in range(2):
    test_[{'y': k}] = test.isel(y=slice(None, k + 1)).sum('y')
print test_.transpose('x', 'y', 'z')

<xarray.DataArray (x: 3, y: 2, z: 2)>
array([[[  2.41920000e+04,   1.34400000e+03],
        [  1.20960000e+05,   6.72000000e+03]],

       [[  4.83840000e+04,   2.68800000e+03],
        [  2.41920000e+05,   1.34400000e+04]],

       [[  1.00800000e+03,   5.60000000e+01],
        [  5.04000000e+03,   2.80000000e+02]]])
Coordinates:
  * x        (x) int64 0 1 2
  * y        (y) int64 0 1
  * z        (z) int64 0 1


In [168]:
test_ = test.copy(deep=True)
test_ = test_.transpose('z', 'x', 'y')
for k in range(2):
    ignore, assign = xr.broadcast(test_[{'y': k}], test.isel(y=slice(None, k + 1)).sum('y'))
    test_[{'y': k}] = assign
    #test_[{'y': k}] = test.isel(y=slice(None, k + 1)).sum('y') # Throws exception (should this, or should it broadcast automatically?)
print test_.transpose('x', 'y', 'z')

<xarray.DataArray (x: 3, y: 2, z: 2)>
array([[[  2.41920000e+04,   1.34400000e+03],
        [  1.20960000e+05,   6.72000000e+03]],

       [[  4.83840000e+04,   2.68800000e+03],
        [  2.41920000e+05,   1.34400000e+04]],

       [[  1.00800000e+03,   5.60000000e+01],
        [  5.04000000e+03,   2.80000000e+02]]])
Coordinates:
  * x        (x) int64 0 1 2
  * y        (y) int64 0 1
  * z        (z) int64 0 1
